### ISSUE TITLE
Update composer.json wp-graphql-gravity-forms dependency

### ISSUE THREAD

**Issue by justlevine** [WebDevStudios/wds-headless-wordpress#11]
Noticed `composer.json` is requiring `"harness-software/wp-graphql-gravity-forms": "dev-master"`.

WPGraphQL for Gravity Forms, [is finally on packagist and using semVer](https://packagist.org/packages/harness-software/wp-graphql-gravity-forms), so you might want to consider changing this so you can use the latest version.

(PS: while v0.3.0 is backwards compatible with `dev-main`, you're using the now non-existent master branch; should still be fine, depending on how long ago the last update was).

**Comment by gregrickaby** [comment]
@justlevine I'm getting this error:

```bash
➜  wp-content git:(feature/wpgraphql-gravity-forms) ✗ composer require harness-software/wp-graphql-gravity-forms 
                                                                                            
  [InvalidArgumentException]                                                                                                       
  Package harness-software/wp-graphql-gravity-forms at version has a PHP requirement incompatible with your PHP version (7.3.24)
```

I'm running PHP 7.4
