### ISSUE TITLE
Internal links in blocks do not use FE domain

### ISSUE THREAD

**Issue by ravewebdev** [WebDevStudios/wds-headless-wordpress#23]
When adding a link to text or a block in the Block Editor, links to other site posts/pages use the WP/BE domain instead of the FE domain. This will need to be modified to use the FE domain (similar to how it's done in the View Post permalink domain) so links work properly on the FE. Currently, these links just redirect to the FE homepage instead.

![Screen Shot 2021-04-22 at 10 28 57 AM](https://user-images.githubusercontent.com/36422618/115750895-e1286280-a355-11eb-82e0-86efa885f9ee.png)

**Comment by donmhico** [comment]
I've been looking into this and there are a few approach in mind.

1. The link results are from `/wp/v2/search` as seen [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/fetch/__experimental-fetch-link-suggestions.js). So we can change URLs of the search results on Search endpoint. The trade-off is, while we are just editing the URLs of post types results, the[ official docs](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#important-note-about-changing-responses) discourages modifying responses of core endpoints.

2. "Links" are saved as _normal post content_  and not some block attributes. We can perform search and replace action on post save.

3. Create our own URL Input implementation so it will hit our own search endpoint which handles the URLs. This way we won't need to modify `wp/v2/search` endpoint. I've been trying to find a way to modify / filter the built-in URL Input but I can't seem to find a way to do so.

References:
- https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/url-input/index.js
- https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/url-input/button.js
