### ISSUE TITLE
Convert headless theme to plugin

### ISSUE THREAD

**Issue by ravewebdev** [WebDevStudios/wds-headless-wordpress#42]
(Tentative plan as of 2021/08/20)
Break current headless theme into separate plugins then extract into individual packages (for installation via composer) based on the following:

- [x] `wds-headless-core` for the base headlesss plugin functionality (e.g., permalink handling, settings)
- [ ] `wds-headless-blocks` for block customizations / custom blocks
- [ ] `wds-headless-acf` for Advanced Custom Fields integration
- [ ] `wds-headless-algolia` for WP Search with Algolia integration
- [ ] `wds-headless-gravityforms` for Gravity Forms integration
- [ ] `wds-headless-seo` for Yoast SEO integration
- [x] remove CPT handling - to be set up on a project-by-project basis (e.g., via CPT UI or Atlas Content Modeler?)

**Comment by ravewebdev** [comment]
EOD
- Planned out tentative breakdown of new plugins from current headless theme
- Set up `wds-headless-core` plugin structure, started copying over base headless functionality

**Comment by gregrickaby** [comment]
Thank you for laying all this out. Let's chat about repo setup.

I don't think any of us wants to keep track of/maintain 7+ Github repos. Do we want to use a monorepo to manage all the add-ons? Or stick with our normal multi-repo?

Monorepo Pros:

1. All of these add-ons will depend on and extend a single plugin
2. Our dev team is small, so it will be easier to onboard others
3. CI and testing will be much easier with a single repo 

Monorepo Cons:

1. Configuring Composer/Packagist could be very complex 😬 

A quick search:

- https://beberlei.de/2015/04/11/monolithic_repositories_with_php_and_composer.html
- https://blog.packagist.com/installing-composer-packages-from-monorepos/

Thoughts @ravewebdev?

**Comment by ravewebdev** [comment]
@gregrickaby I think the monorepo setup could work, assuming we can get everything working with Composer. I definitely think splitting things up (so we don't just have a single, massive dependency for people to have to deal with) is the way to go, especially if we want end users to be able to pick and choose what to install, but I agree that having multiple repos would likely get out of hand easily.

If we try the monorepo route, would we include the base/core plugin in it as well? I think that would make the most sense, if possible.

Also, I was initially envisioning the splitting of this repo to mirror how we discussed splitting the frontend headless repo. If we go with a monorepo here, should we do the same over there?

**Comment by ravewebdev** [comment]
8/24 EOD
- Finished breaking core functionality out into `wds-headless-core` plugin

**Comment by ravewebdev** [comment]
8/25 EOD
- Removed code-based CPT registration in favor of CPT UI for now
- Updated "core" plugin requirements via TGM
- Added activation/deactivation hooks to core plugin
- Updated namespace, constants for core plugin
- Set up "blocks" plugin structure

**Comment by ravewebdev** [comment]
Closed as superseded by https://github.com/WebDevStudios/nextjs-wordpress-starter/issues/607
